/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_medecin (void)
{
  GtkWidget *medecin;
  GtkWidget *fixed1;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *label11;
  GtkWidget *label10;
  GtkWidget *label9;
  GtkWidget *label8;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *label5;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *label1;
  GtkWidget *button1;
  GtkWidget *label2;

  medecin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (medecin, "medecin");
  gtk_window_set_title (GTK_WINDOW (medecin), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_set_name (fixed1, "fixed1");
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (medecin), fixed1);

  label3 = gtk_label_new (_("prenom"));
  gtk_widget_set_name (label3, "label3");
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 16, 96);
  gtk_widget_set_size_request (label3, 64, 24);

  label4 = gtk_label_new (_("age"));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 16, 128);
  gtk_widget_set_size_request (label4, 41, 17);

  entry1 = gtk_entry_new ();
  gtk_widget_set_name (entry1, "entry1");
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 64, 64);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_set_name (entry2, "entry2");
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 80, 96);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_set_name (entry3, "entry3");
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 56, 128);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label11 = gtk_label_new (_("num telephone"));
  gtk_widget_set_name (label11, "label11");
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed1), label11, 24, 392);
  gtk_widget_set_size_request (label11, 104, 24);

  label10 = gtk_label_new (_("adresse"));
  gtk_widget_set_name (label10, "label10");
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 24, 360);
  gtk_widget_set_size_request (label10, 64, 24);

  label9 = gtk_label_new (_("etat civil"));
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 16, 320);
  gtk_widget_set_size_request (label9, 72, 24);

  label8 = gtk_label_new (_("salaire"));
  gtk_widget_set_name (label8, "label8");
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 24, 280);
  gtk_widget_set_size_request (label8, 48, 24);

  label7 = gtk_label_new (_("nationalit\303\251"));
  gtk_widget_set_name (label7, "label7");
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 16, 240);
  gtk_widget_set_size_request (label7, 88, 24);

  label6 = gtk_label_new (_("mdp"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 16, 208);
  gtk_widget_set_size_request (label6, 41, 17);

  label5 = gtk_label_new (_("num passport/CIN "));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 16, 168);
  gtk_widget_set_size_request (label5, 136, 24);

  entry4 = gtk_entry_new ();
  gtk_widget_set_name (entry4, "entry4");
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed1), entry4, 152, 168);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_set_name (entry5, "entry5");
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed1), entry5, 56, 208);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_set_name (entry6, "entry6");
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed1), entry6, 104, 240);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_set_name (entry7, "entry7");
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed1), entry7, 80, 280);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_set_name (entry8, "entry8");
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed1), entry8, 88, 320);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_set_name (entry9, "entry9");
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed1), entry9, 88, 360);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_set_name (entry10, "entry10");
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed1), entry10, 136, 392);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label1 = gtk_label_new (_("medecin"));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 136, 16);
  gtk_widget_set_size_request (label1, 128, 24);

  button1 = gtk_button_new_with_mnemonic (_("enregistrer"));
  gtk_widget_set_name (button1, "button1");
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 8, 432);
  gtk_widget_set_size_request (button1, 96, 32);

  label2 = gtk_label_new (_("nom"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 8, 64);
  gtk_widget_set_size_request (label2, 56, 24);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (medecin, medecin, "medecin");
  GLADE_HOOKUP_OBJECT (medecin, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (medecin, label3, "label3");
  GLADE_HOOKUP_OBJECT (medecin, label4, "label4");
  GLADE_HOOKUP_OBJECT (medecin, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (medecin, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (medecin, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (medecin, label11, "label11");
  GLADE_HOOKUP_OBJECT (medecin, label10, "label10");
  GLADE_HOOKUP_OBJECT (medecin, label9, "label9");
  GLADE_HOOKUP_OBJECT (medecin, label8, "label8");
  GLADE_HOOKUP_OBJECT (medecin, label7, "label7");
  GLADE_HOOKUP_OBJECT (medecin, label6, "label6");
  GLADE_HOOKUP_OBJECT (medecin, label5, "label5");
  GLADE_HOOKUP_OBJECT (medecin, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (medecin, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (medecin, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (medecin, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (medecin, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (medecin, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (medecin, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (medecin, label1, "label1");
  GLADE_HOOKUP_OBJECT (medecin, button1, "button1");
  GLADE_HOOKUP_OBJECT (medecin, label2, "label2");

  return medecin;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *fixed3;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *entry13;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *entry14;
  GtkWidget *entry15;
  GtkWidget *entry16;
  GtkWidget *entry17;
  GtkWidget *entry18;
  GtkWidget *entry19;
  GtkWidget *entry20;
  GtkWidget *label22;
  GtkWidget *button2;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window2, "window2");
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_set_name (fixed2, "fixed2");
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_set_name (fixed3, "fixed3");
  gtk_widget_show (fixed3);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed3, 0, 0);
  gtk_widget_set_size_request (fixed3, 0, 0);

  label12 = gtk_label_new (_("nom"));
  gtk_widget_set_name (label12, "label12");
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 8, 64);
  gtk_widget_set_size_request (label12, 56, 24);

  label13 = gtk_label_new (_("prenom"));
  gtk_widget_set_name (label13, "label13");
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 16, 96);
  gtk_widget_set_size_request (label13, 64, 24);

  label14 = gtk_label_new (_("age"));
  gtk_widget_set_name (label14, "label14");
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 16, 128);
  gtk_widget_set_size_request (label14, 41, 17);

  entry11 = gtk_entry_new ();
  gtk_widget_set_name (entry11, "entry11");
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed3), entry11, 64, 64);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_set_name (entry12, "entry12");
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed3), entry12, 80, 96);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  entry13 = gtk_entry_new ();
  gtk_widget_set_name (entry13, "entry13");
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed3), entry13, 56, 128);
  gtk_widget_set_size_request (entry13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  label15 = gtk_label_new (_("num telephone"));
  gtk_widget_set_name (label15, "label15");
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 24, 392);
  gtk_widget_set_size_request (label15, 104, 24);

  label16 = gtk_label_new (_("adresse"));
  gtk_widget_set_name (label16, "label16");
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 24, 360);
  gtk_widget_set_size_request (label16, 64, 24);

  label17 = gtk_label_new (_("etat civil"));
  gtk_widget_set_name (label17, "label17");
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 16, 320);
  gtk_widget_set_size_request (label17, 72, 24);

  label18 = gtk_label_new (_("salaire"));
  gtk_widget_set_name (label18, "label18");
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 24, 280);
  gtk_widget_set_size_request (label18, 48, 24);

  label19 = gtk_label_new (_("nationalit\303\251"));
  gtk_widget_set_name (label19, "label19");
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 16, 240);
  gtk_widget_set_size_request (label19, 88, 24);

  label20 = gtk_label_new (_("mdp"));
  gtk_widget_set_name (label20, "label20");
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 16, 208);
  gtk_widget_set_size_request (label20, 41, 17);

  label21 = gtk_label_new (_("num passport/CIN "));
  gtk_widget_set_name (label21, "label21");
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 16, 168);
  gtk_widget_set_size_request (label21, 136, 24);

  entry14 = gtk_entry_new ();
  gtk_widget_set_name (entry14, "entry14");
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed3), entry14, 152, 168);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  entry15 = gtk_entry_new ();
  gtk_widget_set_name (entry15, "entry15");
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed3), entry15, 56, 208);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  entry16 = gtk_entry_new ();
  gtk_widget_set_name (entry16, "entry16");
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed3), entry16, 104, 240);
  gtk_widget_set_size_request (entry16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  entry17 = gtk_entry_new ();
  gtk_widget_set_name (entry17, "entry17");
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed3), entry17, 80, 280);
  gtk_widget_set_size_request (entry17, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  entry18 = gtk_entry_new ();
  gtk_widget_set_name (entry18, "entry18");
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed3), entry18, 88, 320);
  gtk_widget_set_size_request (entry18, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  entry19 = gtk_entry_new ();
  gtk_widget_set_name (entry19, "entry19");
  gtk_widget_show (entry19);
  gtk_fixed_put (GTK_FIXED (fixed3), entry19, 88, 360);
  gtk_widget_set_size_request (entry19, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  entry20 = gtk_entry_new ();
  gtk_widget_set_name (entry20, "entry20");
  gtk_widget_show (entry20);
  gtk_fixed_put (GTK_FIXED (fixed3), entry20, 136, 392);
  gtk_widget_set_size_request (entry20, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  label22 = gtk_label_new (_("infirmier"));
  gtk_widget_set_name (label22, "label22");
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 136, 16);
  gtk_widget_set_size_request (label22, 128, 24);

  button2 = gtk_button_new_with_mnemonic (_("enregistrer"));
  gtk_widget_set_name (button2, "button2");
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed3), button2, 128, 448);
  gtk_widget_set_size_request (button2, 96, 32);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, label14, "label14");
  GLADE_HOOKUP_OBJECT (window2, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (window2, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (window2, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");
  GLADE_HOOKUP_OBJECT (window2, label16, "label16");
  GLADE_HOOKUP_OBJECT (window2, label17, "label17");
  GLADE_HOOKUP_OBJECT (window2, label18, "label18");
  GLADE_HOOKUP_OBJECT (window2, label19, "label19");
  GLADE_HOOKUP_OBJECT (window2, label20, "label20");
  GLADE_HOOKUP_OBJECT (window2, label21, "label21");
  GLADE_HOOKUP_OBJECT (window2, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (window2, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (window2, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (window2, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (window2, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (window2, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (window2, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (window2, label22, "label22");
  GLADE_HOOKUP_OBJECT (window2, button2, "button2");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed4;
  GtkWidget *fixed5;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *entry21;
  GtkWidget *entry22;
  GtkWidget *entry23;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *entry24;
  GtkWidget *entry25;
  GtkWidget *entry26;
  GtkWidget *entry27;
  GtkWidget *entry28;
  GtkWidget *entry29;
  GtkWidget *entry30;
  GtkWidget *label33;
  GtkWidget *button3;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window3, "window3");
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_set_name (fixed4, "fixed4");
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window3), fixed4);

  fixed5 = gtk_fixed_new ();
  gtk_widget_set_name (fixed5, "fixed5");
  gtk_widget_show (fixed5);
  gtk_fixed_put (GTK_FIXED (fixed4), fixed5, 0, 0);
  gtk_widget_set_size_request (fixed5, 0, 0);

  label23 = gtk_label_new (_("nom"));
  gtk_widget_set_name (label23, "label23");
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed5), label23, 8, 64);
  gtk_widget_set_size_request (label23, 56, 24);

  label24 = gtk_label_new (_("prenom"));
  gtk_widget_set_name (label24, "label24");
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed5), label24, 16, 96);
  gtk_widget_set_size_request (label24, 64, 24);

  label25 = gtk_label_new (_("age"));
  gtk_widget_set_name (label25, "label25");
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 16, 128);
  gtk_widget_set_size_request (label25, 41, 17);

  entry21 = gtk_entry_new ();
  gtk_widget_set_name (entry21, "entry21");
  gtk_widget_show (entry21);
  gtk_fixed_put (GTK_FIXED (fixed5), entry21, 64, 64);
  gtk_widget_set_size_request (entry21, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 8226);

  entry22 = gtk_entry_new ();
  gtk_widget_set_name (entry22, "entry22");
  gtk_widget_show (entry22);
  gtk_fixed_put (GTK_FIXED (fixed5), entry22, 80, 96);
  gtk_widget_set_size_request (entry22, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22), 8226);

  entry23 = gtk_entry_new ();
  gtk_widget_set_name (entry23, "entry23");
  gtk_widget_show (entry23);
  gtk_fixed_put (GTK_FIXED (fixed5), entry23, 56, 128);
  gtk_widget_set_size_request (entry23, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry23), 8226);

  label26 = gtk_label_new (_("num telephone"));
  gtk_widget_set_name (label26, "label26");
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 24, 392);
  gtk_widget_set_size_request (label26, 104, 24);

  label27 = gtk_label_new (_("adresse"));
  gtk_widget_set_name (label27, "label27");
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 24, 360);
  gtk_widget_set_size_request (label27, 64, 24);

  label28 = gtk_label_new (_("etat civil"));
  gtk_widget_set_name (label28, "label28");
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 16, 320);
  gtk_widget_set_size_request (label28, 72, 24);

  label29 = gtk_label_new (_("salaire"));
  gtk_widget_set_name (label29, "label29");
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 24, 280);
  gtk_widget_set_size_request (label29, 48, 24);

  label30 = gtk_label_new (_("nationalit\303\251"));
  gtk_widget_set_name (label30, "label30");
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 16, 240);
  gtk_widget_set_size_request (label30, 88, 24);

  label31 = gtk_label_new (_("mdp"));
  gtk_widget_set_name (label31, "label31");
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 16, 208);
  gtk_widget_set_size_request (label31, 41, 17);

  label32 = gtk_label_new (_("num passport/CIN "));
  gtk_widget_set_name (label32, "label32");
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 16, 168);
  gtk_widget_set_size_request (label32, 136, 24);

  entry24 = gtk_entry_new ();
  gtk_widget_set_name (entry24, "entry24");
  gtk_widget_show (entry24);
  gtk_fixed_put (GTK_FIXED (fixed5), entry24, 152, 168);
  gtk_widget_set_size_request (entry24, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry24), 8226);

  entry25 = gtk_entry_new ();
  gtk_widget_set_name (entry25, "entry25");
  gtk_widget_show (entry25);
  gtk_fixed_put (GTK_FIXED (fixed5), entry25, 56, 208);
  gtk_widget_set_size_request (entry25, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 8226);

  entry26 = gtk_entry_new ();
  gtk_widget_set_name (entry26, "entry26");
  gtk_widget_show (entry26);
  gtk_fixed_put (GTK_FIXED (fixed5), entry26, 104, 240);
  gtk_widget_set_size_request (entry26, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  entry27 = gtk_entry_new ();
  gtk_widget_set_name (entry27, "entry27");
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed5), entry27, 80, 280);
  gtk_widget_set_size_request (entry27, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  entry28 = gtk_entry_new ();
  gtk_widget_set_name (entry28, "entry28");
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (fixed5), entry28, 88, 320);
  gtk_widget_set_size_request (entry28, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  entry29 = gtk_entry_new ();
  gtk_widget_set_name (entry29, "entry29");
  gtk_widget_show (entry29);
  gtk_fixed_put (GTK_FIXED (fixed5), entry29, 88, 360);
  gtk_widget_set_size_request (entry29, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  entry30 = gtk_entry_new ();
  gtk_widget_set_name (entry30, "entry30");
  gtk_widget_show (entry30);
  gtk_fixed_put (GTK_FIXED (fixed5), entry30, 136, 392);
  gtk_widget_set_size_request (entry30, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 8226);

  label33 = gtk_label_new (_("agent"));
  gtk_widget_set_name (label33, "label33");
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 136, 16);
  gtk_widget_set_size_request (label33, 128, 24);

  button3 = gtk_button_new_with_mnemonic (_("enregistrer"));
  gtk_widget_set_name (button3, "button3");
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed5), button3, 128, 448);
  gtk_widget_set_size_request (button3, 96, 32);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window3, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window3, label23, "label23");
  GLADE_HOOKUP_OBJECT (window3, label24, "label24");
  GLADE_HOOKUP_OBJECT (window3, label25, "label25");
  GLADE_HOOKUP_OBJECT (window3, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (window3, entry22, "entry22");
  GLADE_HOOKUP_OBJECT (window3, entry23, "entry23");
  GLADE_HOOKUP_OBJECT (window3, label26, "label26");
  GLADE_HOOKUP_OBJECT (window3, label27, "label27");
  GLADE_HOOKUP_OBJECT (window3, label28, "label28");
  GLADE_HOOKUP_OBJECT (window3, label29, "label29");
  GLADE_HOOKUP_OBJECT (window3, label30, "label30");
  GLADE_HOOKUP_OBJECT (window3, label31, "label31");
  GLADE_HOOKUP_OBJECT (window3, label32, "label32");
  GLADE_HOOKUP_OBJECT (window3, entry24, "entry24");
  GLADE_HOOKUP_OBJECT (window3, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (window3, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (window3, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (window3, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (window3, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (window3, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (window3, label33, "label33");
  GLADE_HOOKUP_OBJECT (window3, button3, "button3");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed6;
  GtkWidget *fixed7;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *entry31;
  GtkWidget *entry32;
  GtkWidget *entry33;
  GtkWidget *entry34;
  GtkWidget *entry35;
  GtkWidget *entry36;
  GtkWidget *entry37;
  GtkWidget *entry38;
  GtkWidget *entry39;
  GtkWidget *entry40;
  GtkWidget *label41;
  GtkWidget *label43;
  GtkWidget *label38;
  GtkWidget *label37;
  GtkWidget *label39;
  GtkWidget *label42;
  GtkWidget *label40;
  GtkWidget *label45;
  GtkWidget *entry41;
  GtkWidget *label44;
  GtkWidget *label46;
  GtkWidget *entry42;
  GtkWidget *entry43;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *entry44;
  GtkWidget *label49;
  GtkWidget *entry45;
  GtkWidget *button4;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window4, "window4");
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_set_name (fixed6, "fixed6");
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window4), fixed6);

  fixed7 = gtk_fixed_new ();
  gtk_widget_set_name (fixed7, "fixed7");
  gtk_widget_show (fixed7);
  gtk_fixed_put (GTK_FIXED (fixed6), fixed7, 120, 0);
  gtk_widget_set_size_request (fixed7, 496, 544);

  label34 = gtk_label_new (_("nom"));
  gtk_widget_set_name (label34, "label34");
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed7), label34, 8, 64);
  gtk_widget_set_size_request (label34, 56, 24);

  label35 = gtk_label_new (_("prenom"));
  gtk_widget_set_name (label35, "label35");
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed7), label35, 16, 96);
  gtk_widget_set_size_request (label35, 64, 24);

  label36 = gtk_label_new (_("age"));
  gtk_widget_set_name (label36, "label36");
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed7), label36, 16, 128);
  gtk_widget_set_size_request (label36, 41, 17);

  entry31 = gtk_entry_new ();
  gtk_widget_set_name (entry31, "entry31");
  gtk_widget_show (entry31);
  gtk_fixed_put (GTK_FIXED (fixed7), entry31, 64, 64);
  gtk_widget_set_size_request (entry31, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry31), 8226);

  entry32 = gtk_entry_new ();
  gtk_widget_set_name (entry32, "entry32");
  gtk_widget_show (entry32);
  gtk_fixed_put (GTK_FIXED (fixed7), entry32, 80, 96);
  gtk_widget_set_size_request (entry32, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry32), 8226);

  entry33 = gtk_entry_new ();
  gtk_widget_set_name (entry33, "entry33");
  gtk_widget_show (entry33);
  gtk_fixed_put (GTK_FIXED (fixed7), entry33, 56, 128);
  gtk_widget_set_size_request (entry33, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry33), 8226);

  entry34 = gtk_entry_new ();
  gtk_widget_set_name (entry34, "entry34");
  gtk_widget_show (entry34);
  gtk_fixed_put (GTK_FIXED (fixed7), entry34, 104, 168);
  gtk_widget_set_size_request (entry34, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry34), 8226);

  entry35 = gtk_entry_new ();
  gtk_widget_set_name (entry35, "entry35");
  gtk_widget_show (entry35);
  gtk_fixed_put (GTK_FIXED (fixed7), entry35, 152, 208);
  gtk_widget_set_size_request (entry35, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry35), 8226);

  entry36 = gtk_entry_new ();
  gtk_widget_set_name (entry36, "entry36");
  gtk_widget_show (entry36);
  gtk_fixed_put (GTK_FIXED (fixed7), entry36, 88, 240);
  gtk_widget_set_size_request (entry36, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry36), 8226);

  entry37 = gtk_entry_new ();
  gtk_widget_set_name (entry37, "entry37");
  gtk_widget_show (entry37);
  gtk_fixed_put (GTK_FIXED (fixed7), entry37, 144, 280);
  gtk_widget_set_size_request (entry37, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry37), 8226);

  entry38 = gtk_entry_new ();
  gtk_widget_set_name (entry38, "entry38");
  gtk_widget_show (entry38);
  gtk_fixed_put (GTK_FIXED (fixed7), entry38, 88, 320);
  gtk_widget_set_size_request (entry38, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry38), 8226);

  entry39 = gtk_entry_new ();
  gtk_widget_set_name (entry39, "entry39");
  gtk_widget_show (entry39);
  gtk_fixed_put (GTK_FIXED (fixed7), entry39, 120, 360);
  gtk_widget_set_size_request (entry39, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry39), 8226);

  entry40 = gtk_entry_new ();
  gtk_widget_set_name (entry40, "entry40");
  gtk_widget_show (entry40);
  gtk_fixed_put (GTK_FIXED (fixed7), entry40, 96, 392);
  gtk_widget_set_size_request (entry40, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry40), 8226);

  label41 = gtk_label_new (_("nationalit\303\251"));
  gtk_widget_set_name (label41, "label41");
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed7), label41, 16, 168);
  gtk_widget_set_size_request (label41, 88, 24);

  label43 = gtk_label_new (_("num passport/CIN "));
  gtk_widget_set_name (label43, "label43");
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed7), label43, 16, 208);
  gtk_widget_set_size_request (label43, 136, 24);

  label38 = gtk_label_new (_("adresse"));
  gtk_widget_set_name (label38, "label38");
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed7), label38, 16, 240);
  gtk_widget_set_size_request (label38, 64, 24);

  label37 = gtk_label_new (_("contact urgence"));
  gtk_widget_set_name (label37, "label37");
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed7), label37, 16, 280);
  gtk_widget_set_size_request (label37, 120, 24);

  label39 = gtk_label_new (_("poids"));
  gtk_widget_set_name (label39, "label39");
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed7), label39, 16, 320);
  gtk_widget_set_size_request (label39, 72, 24);

  label42 = gtk_label_new (_("taille en cm"));
  gtk_widget_set_name (label42, "label42");
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed7), label42, 24, 360);
  gtk_widget_set_size_request (label42, 88, 24);

  label40 = gtk_label_new (_("sexe"));
  gtk_widget_set_name (label40, "label40");
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed7), label40, 24, 392);
  gtk_widget_set_size_request (label40, 48, 24);

  label45 = gtk_label_new (_("type de sang"));
  gtk_widget_set_name (label45, "label45");
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed7), label45, 32, 432);
  gtk_widget_set_size_request (label45, 88, 24);

  entry41 = gtk_entry_new ();
  gtk_widget_set_name (entry41, "entry41");
  gtk_widget_show (entry41);
  gtk_fixed_put (GTK_FIXED (fixed7), entry41, 128, 432);
  gtk_widget_set_size_request (entry41, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry41), 8226);

  label44 = gtk_label_new (_("patient"));
  gtk_widget_set_name (label44, "label44");
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed7), label44, 136, 16);
  gtk_widget_set_size_request (label44, 128, 24);

  label46 = gtk_label_new (_("allergies"));
  gtk_widget_set_name (label46, "label46");
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed7), label46, 32, 472);
  gtk_widget_set_size_request (label46, 72, 24);

  entry42 = gtk_entry_new ();
  gtk_widget_set_name (entry42, "entry42");
  gtk_widget_show (entry42);
  gtk_fixed_put (GTK_FIXED (fixed7), entry42, 104, 472);
  gtk_widget_set_size_request (entry42, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry42), 8226);

  entry43 = gtk_entry_new ();
  gtk_widget_set_name (entry43, "entry43");
  gtk_widget_show (entry43);
  gtk_fixed_put (GTK_FIXED (fixed7), entry43, 312, 64);
  gtk_widget_set_size_request (entry43, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry43), 8226);

  label47 = gtk_label_new (_("etat"));
  gtk_widget_set_name (label47, "label47");
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed7), label47, 264, 64);
  gtk_widget_set_size_request (label47, 56, 24);

  label48 = gtk_label_new (_("date entr\303\251e"));
  gtk_widget_set_name (label48, "label48");
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed7), label48, 248, 96);
  gtk_widget_set_size_request (label48, 88, 24);

  entry44 = gtk_entry_new ();
  gtk_widget_set_name (entry44, "entry44");
  gtk_widget_show (entry44);
  gtk_fixed_put (GTK_FIXED (fixed7), entry44, 336, 96);
  gtk_widget_set_size_request (entry44, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry44), 8226);

  label49 = gtk_label_new (_("date sortie"));
  gtk_widget_set_name (label49, "label49");
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed7), label49, 224, 128);
  gtk_widget_set_size_request (label49, 88, 24);

  entry45 = gtk_entry_new ();
  gtk_widget_set_name (entry45, "entry45");
  gtk_widget_show (entry45);
  gtk_fixed_put (GTK_FIXED (fixed7), entry45, 312, 128);
  gtk_widget_set_size_request (entry45, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry45), 8226);

  button4 = gtk_button_new_with_mnemonic (_("enregistrer"));
  gtk_widget_set_name (button4, "button4");
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed7), button4, 136, 504);
  gtk_widget_set_size_request (button4, 96, 32);

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window4, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window4, label34, "label34");
  GLADE_HOOKUP_OBJECT (window4, label35, "label35");
  GLADE_HOOKUP_OBJECT (window4, label36, "label36");
  GLADE_HOOKUP_OBJECT (window4, entry31, "entry31");
  GLADE_HOOKUP_OBJECT (window4, entry32, "entry32");
  GLADE_HOOKUP_OBJECT (window4, entry33, "entry33");
  GLADE_HOOKUP_OBJECT (window4, entry34, "entry34");
  GLADE_HOOKUP_OBJECT (window4, entry35, "entry35");
  GLADE_HOOKUP_OBJECT (window4, entry36, "entry36");
  GLADE_HOOKUP_OBJECT (window4, entry37, "entry37");
  GLADE_HOOKUP_OBJECT (window4, entry38, "entry38");
  GLADE_HOOKUP_OBJECT (window4, entry39, "entry39");
  GLADE_HOOKUP_OBJECT (window4, entry40, "entry40");
  GLADE_HOOKUP_OBJECT (window4, label41, "label41");
  GLADE_HOOKUP_OBJECT (window4, label43, "label43");
  GLADE_HOOKUP_OBJECT (window4, label38, "label38");
  GLADE_HOOKUP_OBJECT (window4, label37, "label37");
  GLADE_HOOKUP_OBJECT (window4, label39, "label39");
  GLADE_HOOKUP_OBJECT (window4, label42, "label42");
  GLADE_HOOKUP_OBJECT (window4, label40, "label40");
  GLADE_HOOKUP_OBJECT (window4, label45, "label45");
  GLADE_HOOKUP_OBJECT (window4, entry41, "entry41");
  GLADE_HOOKUP_OBJECT (window4, label44, "label44");
  GLADE_HOOKUP_OBJECT (window4, label46, "label46");
  GLADE_HOOKUP_OBJECT (window4, entry42, "entry42");
  GLADE_HOOKUP_OBJECT (window4, entry43, "entry43");
  GLADE_HOOKUP_OBJECT (window4, label47, "label47");
  GLADE_HOOKUP_OBJECT (window4, label48, "label48");
  GLADE_HOOKUP_OBJECT (window4, entry44, "entry44");
  GLADE_HOOKUP_OBJECT (window4, label49, "label49");
  GLADE_HOOKUP_OBJECT (window4, entry45, "entry45");
  GLADE_HOOKUP_OBJECT (window4, button4, "button4");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed8;
  GtkWidget *label51;
  GtkWidget *label50;
  GtkWidget *entry46;
  GtkWidget *entry47;
  GtkWidget *label52;
  GtkWidget *button5;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window5, "window5");
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_set_name (fixed8, "fixed8");
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window5), fixed8);

  label51 = gtk_label_new (_("codebarre"));
  gtk_widget_set_name (label51, "label51");
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed8), label51, 24, 160);
  gtk_widget_set_size_request (label51, 72, 24);

  label50 = gtk_label_new (_("nom"));
  gtk_widget_set_name (label50, "label50");
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed8), label50, 16, 128);
  gtk_widget_set_size_request (label50, 56, 24);

  entry46 = gtk_entry_new ();
  gtk_widget_set_name (entry46, "entry46");
  gtk_widget_show (entry46);
  gtk_fixed_put (GTK_FIXED (fixed8), entry46, 64, 128);
  gtk_widget_set_size_request (entry46, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry46), 8226);

  entry47 = gtk_entry_new ();
  gtk_widget_set_name (entry47, "entry47");
  gtk_widget_show (entry47);
  gtk_fixed_put (GTK_FIXED (fixed8), entry47, 104, 160);
  gtk_widget_set_size_request (entry47, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry47), 8226);

  label52 = gtk_label_new (_("medicament"));
  gtk_widget_set_name (label52, "label52");
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed8), label52, 112, 24);
  gtk_widget_set_size_request (label52, 96, 24);

  button5 = gtk_button_new_with_mnemonic (_("add"));
  gtk_widget_set_name (button5, "button5");
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed8), button5, 136, 224);
  gtk_widget_set_size_request (button5, 66, 29);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window5, label51, "label51");
  GLADE_HOOKUP_OBJECT (window5, label50, "label50");
  GLADE_HOOKUP_OBJECT (window5, entry46, "entry46");
  GLADE_HOOKUP_OBJECT (window5, entry47, "entry47");
  GLADE_HOOKUP_OBJECT (window5, label52, "label52");
  GLADE_HOOKUP_OBJECT (window5, button5, "button5");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed9;
  GtkWidget *fixed10;
  GtkWidget *entry48;
  GtkWidget *entry49;
  GtkWidget *label55;
  GtkWidget *label54;
  GtkWidget *label53;
  GtkWidget *button7;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window6, "window6");
  gtk_window_set_title (GTK_WINDOW (window6), _("window6"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_set_name (fixed9, "fixed9");
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window6), fixed9);

  fixed10 = gtk_fixed_new ();
  gtk_widget_set_name (fixed10, "fixed10");
  gtk_widget_show (fixed10);
  gtk_fixed_put (GTK_FIXED (fixed9), fixed10, 0, 0);
  gtk_widget_set_size_request (fixed10, 0, 0);

  entry48 = gtk_entry_new ();
  gtk_widget_set_name (entry48, "entry48");
  gtk_widget_show (entry48);
  gtk_fixed_put (GTK_FIXED (fixed10), entry48, 64, 128);
  gtk_widget_set_size_request (entry48, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry48), 8226);

  entry49 = gtk_entry_new ();
  gtk_widget_set_name (entry49, "entry49");
  gtk_widget_show (entry49);
  gtk_fixed_put (GTK_FIXED (fixed10), entry49, 104, 160);
  gtk_widget_set_size_request (entry49, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry49), 8226);

  label55 = gtk_label_new (_("nourriture"));
  gtk_widget_set_name (label55, "label55");
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed10), label55, 112, 24);
  gtk_widget_set_size_request (label55, 96, 24);

  label54 = gtk_label_new (_("date"));
  gtk_widget_set_name (label54, "label54");
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed10), label54, 16, 128);
  gtk_widget_set_size_request (label54, 56, 24);

  label53 = gtk_label_new (_("quantit\303\251"));
  gtk_widget_set_name (label53, "label53");
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed10), label53, 24, 160);
  gtk_widget_set_size_request (label53, 72, 24);

  button7 = gtk_button_new_with_mnemonic (_("add"));
  gtk_widget_set_name (button7, "button7");
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed9), button7, 136, 224);
  gtk_widget_set_size_request (button7, 66, 29);

  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window6, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window6, entry48, "entry48");
  GLADE_HOOKUP_OBJECT (window6, entry49, "entry49");
  GLADE_HOOKUP_OBJECT (window6, label55, "label55");
  GLADE_HOOKUP_OBJECT (window6, label54, "label54");
  GLADE_HOOKUP_OBJECT (window6, label53, "label53");
  GLADE_HOOKUP_OBJECT (window6, button7, "button7");

  return window6;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GtkWidget *fixed11;
  GtkWidget *label56;
  GtkWidget *button8;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window7, "window7");
  gtk_window_set_title (GTK_WINDOW (window7), _("window7"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_set_name (fixed11, "fixed11");
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (window7), fixed11);

  label56 = gtk_label_new ("");
  gtk_widget_set_name (label56, "label56");
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed11), label56, 8, 64);
  gtk_widget_set_size_request (label56, 384, 232);

  button8 = gtk_button_new_with_mnemonic (_("liste"));
  gtk_widget_set_name (button8, "button8");
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed11), button8, 152, 16);
  gtk_widget_set_size_request (button8, 66, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window7, label56, "label56");
  GLADE_HOOKUP_OBJECT (window7, button8, "button8");

  return window7;
}

